CREATE TABLE IF NOT EXISTS user_config (
  chat_id INTEGER PRIMARY KEY,
  groq_api_key TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
